#
# Recommendation service configuration
#

defaultProduct: P001
defaultUser: unknown

analysisService:
    host: localhost
    port: 8102
    path: /recommendation-db

server:
  applicationConnectors:
    - type: http
      port: 8101
  adminConnectors:
    - type: http
      port: 8201

logging:
  level: DEBUG
  loggers:
    de.codecentric.awesome.recommendation: DEBUG
