#
# Recommendation service configuration
#

defaultProduct: P001
defaultUser: john.doe

analysisService:
    host: localhost
    port: 8102
    path: /get-related
    timeout: 500

server:
  applicationConnectors:
    - type: http
      port: 8101
  adminConnectors:
    - type: http
      port: 8201

logging:
  level: ERROR
  loggers:
    de.codecentric.awesome.recommendation: ERROR
